### ISSUE TITLE
Mod doesn't seem to load

### ISSUE THREAD

**Issue by ZaLiTHkA** [MMike17/ArtOfRally_DamageUI#1]
I just installed the current latest Unity Mod Manager (`0.31.0.0`) along with the current version of this mod (`1.0.1`). it is enabled in the Mod Manager settings but I don't see anything in the game UI...

I have selected the "beta" update channel for art of rally in Steam, could this perhaps be causing a problem here?

checking the logs I do see a few errors, though I'm not familiar with Unity Mod Manager, so I'm not sure what this means. here's an excerpt of the `Player.log` file (as opened from the "Open detailed log" button in the Mod Manager UI):

```
--------------------------------------------StartEvent------------------------------------------------------------ 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[DamageUI] [Error] System.NullReferenceException: Object reference not set to an instance of an object
  at DamageUI.HudManager_ShowStageHud_Patch+<>c.<Postfix>b__0_0 () [0x00000] in <4dc3b246200d4bc09a81c65b3177ce6f>:0 
  at DamageUI.Main.Try (System.Action callback) [0x00007] in <4dc3b246200d4bc09a81c65b3177ce6f>:0 
Starting event with kinematic delay of 0 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Not showing Introduction------------------------------------------------------------ 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

GiveControlToPlayer 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

highest settings 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Starting recording. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Not playing ghost. pendingGhostReplayData:False. currentReplay != null: False. startedGhost: False  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[BetterDamage] [Error] Couldn't find temperature for scene : JapanFreeroam. Defaulting to exact value.
[DamageUI] [Error] System.NullReferenceException: Object reference not set to an instance of an object
  at DamageUI.PerformanceDamage_UpdatePerformanceDamage_Patch+<>c__DisplayClass0_0.<Postfix>b__0 () [0x00010] in <4dc3b246200d4bc09a81c65b3177ce6f>:0 
  at DamageUI.Main.Try (System.Action callback) [0x00007] in <4dc3b246200d4bc09a81c65b3177ce6f>:0 
QuickRestart 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[FASTER] Inactive.
[DamageUI] [Error] System.NullReferenceException: Object reference not set to an instance of an object
  at DamageUI.PerformanceDamage_UpdatePerformanceDamage_Patch+<>c__DisplayClass0_0.<Postfix>b__0 () [0x00010] in <4dc3b246200d4bc09a81c65b3177ce6f>:0 
  at DamageUI.Main.Try (System.Action callback) [0x00007] in <4dc3b246200d4bc09a81c65b3177ce6f>:0 
[DamageUI] [Error] System.NullReferenceException: Object reference not set to an instance of an object
  at DamageUI.PerformanceDamage_UpdatePerformanceDamage_Patch+<>c__DisplayClass0_0.<Postfix>b__0 () [0x00010] in <4dc3b246200d4bc09a81c65b3177ce6f>:0 
  at DamageUI.Main.Try (System.Action callback) [0x00007] in <4dc3b246200d4bc09a81c65b3177ce6f>:0 
-------------------------- 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

PAUSING STAGE 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

-------------------------- 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[DamageUI] [Error] System.NullReferenceException: Object reference not set to an instance of an object
  at DamageUI.HudManager_HideStageHud_Patch+<>c.<Postfix>b__0_0 () [0x00000] in <4dc3b246200d4bc09a81c65b3177ce6f>:0 
  at DamageUI.Main.Try (System.Action callback) [0x00007] in <4dc3b246200d4bc09a81c65b3177ce6f>:0 
[BetterDamage] [Error] Couldn't find temperature for scene : JapanFreeroam. Defaulting to exact value.
[BetterDamage] [Error] Couldn't find temperature for scene : JapanFreeroam. Defaulting to exact value.
NOW PLAYING SONG: dreamtime 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[DamageUI] Inactive.
[DamageUI] Active.
Uploading Odo stats for Freeroam 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
```

**Comment by ZaLiTHkA** [comment]
> I have selected the "beta" update channel for art of rally in Steam, could this perhaps be causing a problem here?

...and nope, it's not this, I just switch to the stable release channel and I still have the same issues.

also tried installing Unity Mod Manager with both "DoorstopProxy" and "Assembly" methods, and both of them result in the same behaviour.

**Comment by MMike17** [comment]
Hey there @ZaLiTHkA.
It's actually a limitation from the game, sorry I should've added that to the documentation ^^'

The game simply does not support parts damaging in Freeroam mode.
You can see in the logs that the Better Damage mod also has error in freeroam.

The Damage UI should show up in all other modes :
- Time attack
- Career
- Custom rally

**Comment by MMike17** [comment]
Just updated the readme file for this mod as well as the Better Damage mod.

Sorry but enabling car damage in Freeroam mode is a daunting task.
I probably won't be fixing/implementing that.

**Comment by ZaLiTHkA** [comment]
hmmm.. ok, while that does make sense, and I don't get any errors in the logs from loading up either a custom rally or a time attack, I still don't see the mod UI in game. :/

**Comment by ZaLiTHkA** [comment]
the mod config for "goodColor" and "badColor" also look all kinds of funky though.

![20241026215103_1](https://github.com/user-attachments/assets/38e34980-ee90-4f4e-ba8e-4ce1f025564f)

in this view, where "badColor" has "white", "grey", "black" and "red" as selected, if I click on "red" it toggles everything "off" except for "while". so maybe I have something else going wrong here?

**Comment by MMike17** [comment]
That does look broken, it shouldn't look like that.

I'm using the Unity Mod Manager 0.28.2 I'll try with the version you're using (0.31.0).
Maybe the new version changed its API and it broke my mod.

**Comment by MMike17** [comment]
Tested the mod on the version 0.31.0 of the mod manager.
The UI shows up in game but the settings are broken.

A bug I thought I fixed had to do with the scale of the UI.
Try changing the "uiScale" and position sliders while in time attack and it should fix it for all game modes.

I'm going to try to fix the settings issue for the new mod manager version.

**Comment by ZaLiTHkA** [comment]
Cool beans, thanks you. I'll test that when I get back home again this
afternoon and let you know what I find.

**Comment by MMike17** [comment]
Just fixed the settings issue in the [1.0.2 release](https://github.com/MMike17/ArtOfRally_DamageUI/releases/tag/v1.0.2).
Also added a "Known issues" in the doc with troubleshooting suggestions.

Sorry again about the bugs ^^'

**Comment by ZaLiTHkA** [comment]
just checked again with your update, and the "good" and "bad" colour selections do appear to work correctly again, thanks for that.

I loaded into a time trial to test, and at first I still did not see the mod UI in game, but then I discovered that the "x" and "y" position sliders actually allow positions to be set that are actually outside of my viewport.

here's a short video of the issue (reduced resolution to get the file size down below 10mb for GitHub): 

https://github.com/user-attachments/assets/c9c38593-e676-4375-b66a-23a7d52e2b15

so when I tested this with the previous mod release, perhaps I just didn't move the "x" position slider far enough to bring it into view? not sure what impact the client device screen resolution might have on this, so just for clarification, my monitor runs at 3440x1440.

also, just FYI, the `info.json` file in the updated mod package still contains `1.0.1` for the version string.

**Comment by MMike17** [comment]
That is so weird.
The code logic uses `Screen.width` and `Screen.height` which should be the dimentions of the screen, so it should never be outside the screen.
Are you using any wide screen size compatibility mod ? Or patch ?

I'll update the build again for the version number.

**Comment by ZaLiTHkA** [comment]
my apologies, only just saw the notification of your message.

art of rally requires no mods or patches for ultra-widescreen support, it works by default.. if there's any WQHD-specific details or debugging output I can gather for you here, please do let me know? I've got no issue at all helping out with that.

**Comment by MMike17** [comment]
No worries.

I have no idea. I never had this kind on problems.
As I said, the engine gives me the screen size, so it should work properly....

I don't think I can solve that, except for the documentation I already added.
